### ISSUE TITLE
Display hash values along with samples when results are displayed

### ISSUE THREAD

**Issue by 3vangel1st** [CERT-Polska/mquery#16]
Could you add the SHA1 value of the file when results are displayed? That way we can also remove the physical samples from the directory ones they are indexed.

**Comment by icedevml** [comment]
@3vangel1st Unfortunately this is not that simple. You do still need the physical samples to be in place, because the indexing process is lossy. In general it is not possible to recover the samples back from the indexes.

Also, the database is designed to work very fast but sometimes it may yield a false positive result. Depending on the query and the contents of your samples, this may happen more or less often.

For that reason mquery takes the search result set and checks the original files with YARA in the final step just to be sure. The original file must be available at this particular moment.

/cc @msm-code

**Comment by msm-code** [comment]
Hi,

I've sent you an email, but I'll copy the details here for bookkeeping purposes:

there are actually two related but distinct systems: mquery and ursadb.
 - ursadb is responsible for indexing files, and after the initial indexing it doesn't need the files - but still keeps the original filename in its metadata. Queries are very fast, but they can return some false-positives.
 - mquery uses ursadb under the hood for querying. When querying for files, it queries ursadb and then checks all the files with yara rule again, to weed out false-positives.

We *could* allow mquery users to skip the additional yara scan step. In this case, mquery may return false positives. If that's OK with you, ping me and I'll be happy to implement this feature in my available time.

OTOH, can you explain why you want to remove the samples after scanning? In our use case (and in the other instances that I know of) people usually just index their "malware NFS". If you store samples in a weird location (like s3 buckets or sth), you can try to mount it with FUSE for ursadb, or (if that's not possible) we can consider adding a plugin support for mquery (so that you'll be able to index files coming from whatever your backing malware storage is).

As for the other part of your question (adding SHA1) - yes, that's doable. Not right now, but it's not hard to implement and we can do it if you're interested. If you remove the physical samples, you'll still need to deal with false positives somehow. Is that OK with you?

What do you think?

**Comment by ITAYC0HEN** [comment]
I suggest renaming this issue to reflect the content. It might be included in #33

**Comment by msm-code** [comment]
There are two ways to approach this problem:

 - implement additional attributes stored along with samples in the backend (something that we considered, but don't want to do this right now)
 - just recalculate the hashes every time they are needed.

I've added tags assuming the second implementation - this means that the physical samples will still be needed after indexing though.

**Comment by msm-code** [comment]
![ss](https://user-images.githubusercontent.com/7026881/81976084-4c3ac680-9628-11ea-88f4-049ed38d7d7b.png)

Hash values are displayed now - though it won't allow you to remove the files after indexing, because they still need to be re-checked with yara (to elliminate false positives).
