### ISSUE TITLE
Clarify that newly added samples should be indexed and that there's not auto-indexing

### ISSUE THREAD

**Issue by ITAYC0HEN** [CERT-Polska/mquery#30]
**Description**
I believe it would be useful to document the fact that new files are not indexed automatically when added to the relevant folder (e.g `/mnt/samples`). Mentioning this in the documentation can be useful, as well as providing an example for a nightly cron job to index the newly added files.

**Comment by msm-code** [comment]
I have this slowly growing idea of adding a "tracked folders" feature to mquery. This will allow users to mark folders on the filesystem (like `/mnt/samples`) as "tracked". They will be periodically scanned for new files and indexed.

This will greatly simplify our deployment (and probably all the others), since running a cyclic cron job is a pain for developers and admins. It will also add some structure to the index and make it easier to manage.

Needs more design though

**Comment by msm-code** [comment]
- Clarified in the documentation
- Added a user-friendly button for re-indexing (it should be enough for small to mid collections)
