### ISSUE TITLE
Add a Copy button for for all hashes, and for each single hash

### ISSUE THREAD

**Issue by ITAYC0HEN** [CERT-Polska/mquery#34]
**Description**
Currently, it is not easy to retrieve the hash of the sample. If you're lucky, the filename is the hash, and then you'll need to copy each filename.
I suggest to add buttons to:
- Copy single hash (might be implemented by clicking on the cell)
- Copy all hashes as
    - Sha256
    - Sha1
    - MD5

![image](https://user-images.githubusercontent.com/20182642/78386181-c289e900-75e5-11ea-9d1d-b7116a136c28.png)

![image](https://user-images.githubusercontent.com/20182642/78386240-e0574e00-75e5-11ea-91c7-079b32bb1079.png)

Related to #33

**Comment by ITAYC0HEN** [comment]
Does not solve this completely because Copy All Hashes wasn't implemented

**Comment by msm-code** [comment]
Right, I've misunderstood this issue and thought that `copy all hashes` means "download a file with all hashes" (done with #163).

Actually I didn't even know that there's an option to copy all hashes. Do you find it useful often? To implement it we'll have to compute all the hashes after the query for every file, or think about caching them somewhere.

I'd like to avoid having too much metadata in mquery (it's not useful for us, because we use mwdb for that), but I can reconsider and/or create a new issue for that if that's important.

**Comment by ITAYC0HEN** [comment]
aren't the hashes there already when displaying the sha256 on the table? Or they are calculated for 20 samples at a time?

**Comment by msm-code** [comment]
Nevermind, looks like I've missed the point twice in a row. I've actually checked VT how it works now,

Yeah, all sha256 hashes are in the db. I don't think we can reuse the endpoint used to download the list of the hashes, but the code will be almost the same. I'll reopen it.
