### ISSUE TITLE
Decrease font size on the interface

### ISSUE THREAD

**Issue by ITAYC0HEN** [CERT-Polska/mquery#35]
**Description**

By default, when showing the job's results mquery uses 16px font as retrieved from the `:root` by specifying `1rem`. For most places in the interface, 16px is too big and causes a simple `./samples/<sha256>` to line-wrap.

I suggest using a 0.75REM (12px) font when possible.

**Before:**

![image](https://user-images.githubusercontent.com/20182642/78386691-b18da780-75e6-11ea-9562-f23549fe41d3.png)

**After:**

![image](https://user-images.githubusercontent.com/20182642/78386737-c2d6b400-75e6-11ea-86cb-82e1345b9b5e.png)

**Before:**

![image](https://user-images.githubusercontent.com/20182642/78386770-d8e47480-75e6-11ea-8b4f-2e5c6c58ede7.png)

**After:**
![image](https://user-images.githubusercontent.com/20182642/78386804-eac61780-75e6-11ea-89a5-fd20c4e70239.png)

**Comment by msm-code** [comment]
While I agree that UI could use a lot of improvements, I'm not sure that decreasing a font size is the solution. My longer term plan was to ask a real frontend developer to review and improve the UI.

I don't want to randomly mess with the UI in the meantime, because the end result will probably still be ugly :P. In other words, I feel like the frontend needs more design as a whole. Putting this on `priority:low` for now.

**Comment by msm-code** [comment]
@ITAYC0HEN both query view and recent jobs view has changed over the last year:

Recent jobs:
![ss](https://user-images.githubusercontent.com/7026881/144145735-3cd5be71-1eb1-4f92-9312-960afa11dabc.png)

Query view:
![ss](https://user-images.githubusercontent.com/7026881/144145772-03160ca7-4d96-4b28-bcfb-d7aa0e5d2e25.png)

Do you think it is OK to close this issue? I think font size is not the problem anymore. I can always open more tickets about more specific issues.
