### ISSUE TITLE
Adding the ability to automatically import zip encrypted files with the famous "infected" password

### ISSUE THREAD

**Issue by adulau** [CERT-Polska/mquery#407]
**Feature Category**

- [ ] Correctness
- [X ] User Interface / User Experience
- [ ] Performance
- [ ] Other (please explain)

**Describe the problem**

If you have a large storage of encrypted malware in ZIP/infected format, mquery won't read those by default.

**Describe the solution you'd like**

Detecting if it's a zip file and brute-force the "infected" at import of samples.

**Describe alternatives you've considered**

**Comment by msm-cert** [comment]
Hi!

Do you have one file per archive, or more?

mquery won't read them by default, but there is a way to achieve what you want using plugins. It's not easy, but doable.

It's not documented step-by-step, but see https://cert-polska.github.io/mquery/docs/plugins.html, especially filter plugins.

The idea is that:

* **when indexing** you extract your files, so for example you extract your archive with sample 1234 to `/mnt/samples/1234-archive.zip`
* you write your filter plugin, and **when querying** when you see a file that ends with `.zip` you extract it.

See https://github.com/CERT-Polska/mquery/blob/master/src/plugins/archive.py for an example.

There is currently no way to do it automatically, but in the next release I plan to make indexing easier. The design stage is not completed yet.  It's possible (but not guaranteed) that mquery plugins will be also supported for ursadb indexing.

It won't be supported by mquery core, since it's already doable using plugins, and since you have to support this in ursadb anyway.

Closing the issue since I don't believe anything in the mquery code must be changed to facilitate this, but feel free to comment (or reopen if you don't agree).
