### ISSUE TITLE
[proposed enhancement] query specific datasets

### ISSUE THREAD

**Issue by raw-data** [CERT-Polska/mquery#5]
Could be interesting having the possibility to query specific datasets before running a query.

Workflow example:

- Select from a drop-down menu a specific dataset/s to query
- copy-paste YARA rule
- run query

Use case:
Scanning paths storing different kind of data, i.e. `known-to-be-good`, `known-to-be-bad`, [...]

**Comment by icedevml** [comment]
Hello,

thanks for your report. This issue was addressed in a slightly different way.

It is very hard to attach any "labels" to the datasets in the current database model, because it would require huge changes in how UrsaDB handles them.

There is a concept of "meta data extractors" introduced in the latest version, where you could write your own plugin and place it in `metadata/` directory, so your matched files will be tagged with additional metadata. This way you can implement your own tagging philosophy which suits you the most, including `known-good` or `known-bad` labels.

However, there is no option to query files according to the metadata, but it may appear in the future.

**Comment by msm-code** [comment]
@raw-data by the way, actually right now it is possible to attach labels to datasets (they're called `taints`). Please take a look at https://github.com/CERT-Polska/mquery/pull/44

The feature needs more polish (there's no easy way to add taints from the frontend), but expect improvements soon.

**Comment by raw-data** [comment]
@msm-code thank you for the heads-up, I will test it in the coming days!
